### PR TITLE
Refactor some test functions to be a bit easier to read

### PR DESCRIPTION
**Pull request by gfredericks**

### CODE REVIEW

**Comment by czan** [comment]
Hey there!

I'm not going to merge this patch, because I'm trying to keep master just for releases, with all development happening on the develop branch. I appreciate the thought, though!

I legitimately don't know what I was thinking when I wrote those functions. I want to give myself the benefit of the doubt and guess that their original implementation deserved the extra complexity and that I changed their behaviour over time, but I don't actually know that that's true.

**Comment by gfredericks** [comment]
So you're saying I shouldn't bother making the PR against the `develop` branch?

**Comment by czan** [comment]
You can if you'd like, but I'm just as happy to make the change myself.

**Comment by gfredericks** [comment]
Oh okay, I misinterpreted your last paragraph.

**Pull request closed without merging**
